model:
  model_path: Qwen/Qwen3-235B-A22B
  attn_implementation: flash_attention_3
  ep_dispatch: deepep
  rmsnorm_mode: compile
  deepep_buffer_size_gb: 2.0
  deepep_num_sms: 48
data:
  datasets:
  - path: dummy
    type: tokenized
    max_seq_len: 64000
  select_columns:
  - input_ids
  - labels
  sample_packing_method: sequential
  sample_packing_sequence_len: 64000
  dataloader_num_workers: 0
  dataloader_pin_memory: false
  pad_to_multiple_of: 4096
train:
  output_dir: outputs/xorl-sim/qwen3_235b_a22b_muon_8node_ep8_efsdp8_deepep
  data_parallel_mode: fsdp2
  ulysses_parallel_size: 8
  expert_parallel_size: 8
  data_parallel_replicate_size: 8
  data_parallel_shard_size: 1
  num_train_epochs: 1
  max_steps: 20
  micro_batch_size: 1
  gradient_accumulation_steps: 1
  optimizer: muon
  optimizer_dtype: bf16
  muon_lr: 0.0001
  muon_momentum: 0.95
  lr: 1.0e-05
  lr_warmup_ratio: 0.0
  lr_decay_style: constant
  lr_decay_ratio: 1.0
  weight_decay: 0.01
  max_grad_norm: 1.0
  enable_mixed_precision: true
  enable_gradient_checkpointing: true
  enable_full_shard: true
  enable_activation_offload: false
  init_device: meta
  load_weights_mode: all_ranks
  enable_full_determinism: false
  seed: 42
  empty_cache_steps: 500
  ckpt_manager: dcp
  save_steps: 0
  save_epochs: 0
  save_hf_weights: false
  log_format: structured
  use_wandb: false
