## Hybrid balanced: cp=2, sp=4, dp=1
model:
  model_path: Qwen/Qwen3-8B
  attn_implementation: flash_attention_3

data:
  datasets:
    - path: dummy
      type: tokenized
      max_seq_len: 8193
  select_columns: [input_ids, labels]
  dataset_prepared_path: last_prepared_dataset
  sample_packing_method: sequential
  sample_packing_sequence_len: 64000
  dataloader_num_workers: 4
  dataloader_prefetch_factor: 2
  dataloader_pin_memory: true

train:
  output_dir: outputs/Qwen3-8B-cp2-sp4-bench
  data_parallel_mode: fsdp2
  ulysses_parallel_size: 4
  ringattn_parallel_size: 2
  data_parallel_replicate_size: 1
  data_parallel_shard_size: 1
  expert_parallel_size: 1

  num_train_epochs: 5
  max_steps: 20

  micro_batch_size: 1
  gradient_accumulation_steps: 1

  optimizer: adamw
  lr: 1.0e-3
  lr_warmup_ratio: 0.001
  lr_decay_style: cosine
  lr_decay_ratio: 1.0
  weight_decay: 0.01

  max_grad_norm: 5.0
  enable_mixed_precision: true
  enable_gradient_checkpointing: true
  enable_full_shard: true
  enable_fsdp_offload: false
  enable_activation_offload: false
  init_device: meta
  load_weights_mode: broadcast
  enable_full_determinism: false
  empty_cache_steps: 500
  ckpt_manager: dcp
  save_steps: 1000
  save_hf_weights: false

  use_wandb: false
